name: neuraldart
description: A Dart library for Neural Networks
version: 1.0.0
homepage: https://github.com/enesdemirag/neuraldart

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  yaml: ^2.2.0

dev_dependencies:
  build_runner: ^1.8.0
  build_version: ^2.0.1
  test: ^1.14.2